<a href="https://colab.research.google.com/github/Swayam17o5/DL1/blob/main/DL_B1_15_EXPT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

McCulloch-Pitts (AND GATE)

In [ ]:
# McCulloch-Pitts Neuron for AND Gate (Truth Table)

def step_function(net, threshold):
    if net >= threshold:
        return 1
    else:
        return 0

# Weights and threshold for AND gate
w1 = 1
w2 =-1
threshold = 1.5

print("AND Gate using McCulloch-Pitts Model\n")
print("x1   x2   net   output")
print("----------------------")

# Generate all combinations
for x1 in [0, 1]:
    for x2 in [0, 1]:
        net = (x1 * w1) + (x2 * w2)
        output = step_function(net, threshold)
        print(f"{x1}    {x2}    {net}     {output}")


AND Gate using McCulloch-Pitts Model

x1   x2   net   output
----------------------
0    0    0     0
0    1    1     0
1    0    1     0
1    1    2     1


McCulloch-Pitts (OR GATE)

In [ ]:
# McCulloch-Pitts Neuron for OR Gate (Truth Table)

def step_function(net, threshold):
    if net >= threshold:
        return 1
    else:
        return 0

# Weights and threshold for AND gate
w1 = 1
w2 =-1
threshold = 1

print("OR Gate using McCulloch-Pitts Model\n")
print("x1   x2   net   output")
print("----------------------")

# Generate all combinations
for x1 in [0, 1]:
    for x2 in [0, 1]:
        net = (x1 * w1) + (x2 * w2)
        output = step_function(net, threshold)
        print(f"{x1}    {x2}     {net}     {output}")


OR Gate using McCulloch-Pitts Model

x1   x2   net   output
----------------------
0    0     0     0
0    1     -1     0
1    0     1     1
1    1     0     0


McCulloch-Pitts (USE CASE)

In [ ]:
# McCulloch-Pitts Loan Approval System

def step_function(net, threshold):
    if net >= threshold:
        return 1
    else:
        return 0

# Weights
w1 = 1   # Credit Score
w2 = 1   # Income Stability
w3 = 1   # Low Debt

threshold = 2

print("Loan Approval System using McCulloch-Pitts Model\n")
print("x1  x2  x3  net  decision")
print("-------------------------")

for x1 in [0, 1]:
    for x2 in [0, 1]:
        for x3 in [0, 1]:
            net = (x1*w1) + (x2*w2) + (x3*w3)
            output = step_function(net, threshold)
            decision = "Approve" if output == 1 else "Reject"
            print(f"{x1}   {x2}   {x3}   {net}    {decision}")


Loan Approval System using McCulloch-Pitts Model

x1  x2  x3  net  decision
-------------------------
0   0   0   0    Reject
0   0   1   1    Reject
0   1   0   1    Reject
0   1   1   2    Approve
1   0   0   1    Reject
1   0   1   2    Approve
1   1   0   2    Approve
1   1   1   3    Approve


Perceptron Model(AND GATE)

In [ ]:
# AND Gate using Perceptron Learning Algorithm

# Training Data for AND gate
inputs = [(0,0), (0,1), (1,0), (1,1)]
targets = [0, 0, 0, 1]

# Initialize weights and bias
w1 = -1
w2 = 1
bias = 0
learning_rate = 0.1

# Activation Function
def step(net):
    return 1 if net >= 0 else 0

# Training
for epoch in range(10):
    for i in range(len(inputs)):
        x1, x2 = inputs[i]
        target = targets[i]

        net = x1*w1 + x2*w2 + bias
        output = step(net)

        error = target - output

        # Update weights
        w1 = w1 + learning_rate * error * x1
        w2 = w2 + learning_rate * error * x2
        bias = bias + learning_rate * error

print("Trained Weights:")
print("w1 =", w1, " w2 =", w2, " bias =", bias)

# Testing
print("\nAND Gate Results:")
print("x1  x2  output")
print("--------------")

for x1, x2 in inputs:
    net = x1*w1 + x2*w2 + bias
    y = step(net)
    print(f"{x1}   {x2}   {y}")


Trained Weights:
w1 = -0.20000000000000015  w2 = 0.8  bias = -0.30000000000000004

AND Gate Results:
x1  x2  output
--------------
0   0   0
0   1   1
1   0   0
1   1   1


Perceptron (OR GATE)

In [ ]:
# OR Gate using Perceptron Learning Algorithm

# Training Data for OR gate
inputs = [(0,0), (0,1), (1,0), (1,1)]
targets = [0, 1, 1, 1]   # OR gate outputs

# Initialize weights and bias
w1 = 0
w2 = 1
bias = 0
learning_rate = 0.1

# Activation Function
def step(net):
    return 1 if net >= 0 else 0

# Training
for epoch in range(10):
    for i in range(len(inputs)):
        x1, x2 = inputs[i]
        target = targets[i]

        net = x1*w1 + x2*w2 + bias
        output = step(net)

        error = target - output

        # Update weights
        w1 = w1 + learning_rate * error * x1
        w2 = w2 + learning_rate * error * x2
        bias = bias + learning_rate * error

print("Trained Weights:")
print("w1 =", w1, " w2 =", w2, " bias =", bias)

# Testing
print("\nOR Gate Results:")
print("x1  x2  output")
print("--------------")

for x1, x2 in inputs:
    net = x1*w1 + x2*w2 + bias
    y = step(net)
    print(f"{x1}   {x2}   {y}")


Trained Weights:
w1 = 0.1  w2 = 1.0  bias = -0.1

OR Gate Results:
x1  x2  output
--------------
0   0   0
0   1   1
1   0   1
1   1   1


Perceptron Model (USE CASE)

In [ ]:
# Loan Approval System using Perceptron Model (Real-Valued Weights)

# Step Activation Function
def step_function(net):
    if net >= 0:
        return 1
    else:
        return 0

# Real-valued weights (importance levels)
w1 = 2.5   # Credit Score importance
w2 = 1.8   # Income Stability importance
w3 = 1.2   # Low Debt importance

# Bias
bias = -3.0

print("Loan Approval System using Perceptron Model\n")

# Taking user inputs
x1 = int(input("Enter Credit Score Status (1 = Good, 0 = Bad): "))
x2 = int(input("Enter Income Stability (1 = Stable, 0 = Unstable): "))
x3 = int(input("Enter Debt Status (1 = Low Debt, 0 = High Debt): "))

# Net input calculation
net = (x1 * w1) + (x2 * w2) + (x3 * w3) + bias

# Output
output = step_function(net)
decision = "Approve" if output == 1 else "Reject"

print("\n--- Result ---")
print(f"Net Value: {net}")
print(f"Decision: {decision}")


Loan Approval System using Perceptron Model

Enter Credit Score Status (1 = Good, 0 = Bad): 1
Enter Income Stability (1 = Stable, 0 = Unstable): 0
Enter Debt Status (1 = Low Debt, 0 = High Debt): 1

--- Result ---
Net Value: 0.7000000000000002
Decision: Approve


In [ ]:
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0], [1], [1], [0]])

sig = lambda x: 1 / (1 + np.exp(-x))
dsig = lambda x: x * (1 - x)

np.random.seed(1)

w1 = np.random.rand(2, 3)
w2 = np.random.rand(3, 1)

lr = 0.5

for i in range(5000):

    # Forward pass
    h = sig(X @ w1)
    o = sig(h @ w2)

    # Error
    err = Y - o

    # Backpropagation
    w2 += lr * h.T @ (err * dsig(o))
    w1 += lr * X.T @ ((err * dsig(o)) @ w2.T * dsig(h))

    # Print at epoch 1 and 10
    if i == 0:
        print("Epoch 1")
        print("w1 =\n", w1)
        print("w2 =\n", w2)

    if i == 9:
        print("\nEpoch 10")
        print("w1 =\n", w1)
        print("w2 =\n", w2)

print("\nFinal Output:")
print(np.round(o, 3))

Epoch 1
w1 =
 [[ 0.4161105   0.71847888 -0.0027131 ]
 [ 0.30151424  0.14541439  0.08965393]]
w2 =
 [[0.15154525]
 [0.30979298]
 [0.36637397]]

Epoch 10
w1 =
 [[ 0.41462765  0.71231763 -0.01428084]
 [ 0.30019247  0.14203844  0.07857921]]
w2 =
 [[-0.03580757]
 [ 0.11678968]
 [ 0.20206433]]

Final Output:
[[0.075]
 [0.952]
 [0.952]
 [0.025]]
