<a href="https://colab.research.google.com/github/Swayam17o5/DL1/blob/main/McCulloh_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def step_function(net, threshold):
    return 1 if net >= threshold else 0


w1 = 1
w2 = 1
threshold = 2

print("AND Gate using McCulloch-Pitts Model\n")
print("x1   x2   net   output")
print("----------------------")

for x1 in [0, 1]:
    for x2 in [0, 1]:
        net = (x1 * w1) + (x2 * w2)
        output = step_function(net, threshold)
        print(f"{x1}    {x2}    {net}     {output}")

AND Gate using McCulloch-Pitts Model

x1   x2   net   output
----------------------
0    0    0     0
0    1    1     0
1    0    1     0
1    1    2     1


In [2]:
def step_function(net, threshold):
    return 1 if net >= threshold else 0

# Correct weights for OR
w1 = 1
w2 = 1
threshold = 1

print("OR Gate using McCulloch-Pitts Model\n")
print("x1   x2   net   output")
print("----------------------")

for x1 in [0, 1]:
    for x2 in [0, 1]:
        net = (x1 * w1) + (x2 * w2)
        output = step_function(net, threshold)
        print(f"{x1}    {x2}     {net}     {output}")

OR Gate using McCulloch-Pitts Model

x1   x2   net   output
----------------------
0    0     0     0
0    1     1     1
1    0     1     1
1    1     2     1


In [3]:
def step_function(net, threshold):
    return 1 if net >= threshold else 0

w1, w2, w3 = 1, 1, 1
threshold = 2

print("Loan Approval System using McCulloch-Pitts Model\n")
print("x1  x2  x3  net  decision")
print("-------------------------")

for x1 in [0, 1]:
    for x2 in [0, 1]:
        for x3 in [0, 1]:
            net = (x1*w1) + (x2*w2) + (x3*w3)
            output = step_function(net, threshold)
            decision = "Approve" if output == 1 else "Reject"
            print(f"{x1}   {x2}   {x3}   {net}    {decision}")

Loan Approval System using McCulloch-Pitts Model

x1  x2  x3  net  decision
-------------------------
0   0   0   0    Reject
0   0   1   1    Reject
0   1   0   1    Reject
0   1   1   2    Approve
1   0   0   1    Reject
1   0   1   2    Approve
1   1   0   2    Approve
1   1   1   3    Approve


In [4]:
inputs = [(0,0), (0,1), (1,0), (1,1)]
targets = [0, 0, 0, 1]

w1, w2, bias = 0, 0, 0
lr = 0.1

def step(net):
    return 1 if net >= 0 else 0

for epoch in range(10):
    for i in range(len(inputs)):
        x1, x2 = inputs[i]
        target = targets[i]

        net = x1*w1 + x2*w2 + bias
        output = step(net)

        error = target - output

        w1 += lr * error * x1
        w2 += lr * error * x2
        bias += lr * error

print("Trained Weights:")
print("w1 =", w1, " w2 =", w2, " bias =", bias)

print("\nAND Gate Results:")
print("x1  x2  output")
print("--------------")

for x1, x2 in inputs:
    net = x1*w1 + x2*w2 + bias
    print(f"{x1}   {x2}   {step(net)}")

Trained Weights:
w1 = 0.2  w2 = 0.1  bias = -0.20000000000000004

AND Gate Results:
x1  x2  output
--------------
0   0   0
0   1   0
1   0   0
1   1   1


In [5]:
inputs = [(0,0), (0,1), (1,0), (1,1)]
targets = [0, 1, 1, 1]

w1, w2, bias = 0, 0, 0
lr = 0.1

def step(net):
    return 1 if net >= 0 else 0

for epoch in range(10):
    for i in range(len(inputs)):
        x1, x2 = inputs[i]
        target = targets[i]

        net = x1*w1 + x2*w2 + bias
        output = step(net)

        error = target - output

        w1 += lr * error * x1
        w2 += lr * error * x2
        bias += lr * error

print("Trained Weights:")
print("w1 =", w1, " w2 =", w2, " bias =", bias)

print("\nOR Gate Results:")
print("x1  x2  output")
print("--------------")

for x1, x2 in inputs:
    net = x1*w1 + x2*w2 + bias
    print(f"{x1}   {x2}   {step(net)}")

Trained Weights:
w1 = 0.1  w2 = 0.1  bias = -0.1

OR Gate Results:
x1  x2  output
--------------
0   0   0
0   1   1
1   0   1
1   1   1


In [8]:
def step_function(net):
    return 1 if net >= 0 else 0

w1, w2, w3 = 2.5, 1.8, 1.2
bias = -3.0

print("Loan Approval System using Perceptron Model\n")

x1 = int(input("Enter Credit Score Status (1 = Good, 0 = Bad): "))
x2 = int(input("Enter Income Stability (1 = Stable, 0 = Unstable): "))
x3 = int(input("Enter Debt Status (1 = Low Debt, 0 = High Debt): "))

net = (x1 * w1) + (x2 * w2) + (x3 * w3) + bias

decision = "Approve" if step_function(net) == 1 else "Reject"

print("\n--- Result ---")
print(f"Net Value: {net}")
print(f"Decision: {decision}")

Loan Approval System using Perceptron Model

Enter Credit Score Status (1 = Good, 0 = Bad): 1
Enter Income Stability (1 = Stable, 0 = Unstable): 0
Enter Debt Status (1 = Low Debt, 0 = High Debt): 0

--- Result ---
Net Value: -0.5
Decision: Reject


In [7]:
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0], [1], [1], [0]])

sig = lambda x: 1 / (1 + np.exp(-x))
dsig = lambda x: x * (1 - x)

np.random.seed(1)

w1 = np.random.rand(2, 3)
w2 = np.random.rand(3, 1)

lr = 0.5

for i in range(5000):
    h = sig(X @ w1)
    o = sig(h @ w2)

    err = Y - o

    w2 += lr * h.T @ (err * dsig(o))
    w1 += lr * X.T @ ((err * dsig(o)) @ w2.T * dsig(h))

    if i == 0:
        print("Epoch 1\nw1=\n", w1, "\nw2=\n", w2)

    if i == 9:
        print("\nEpoch 10\nw1=\n", w1, "\nw2=\n", w2)

print("\nFinal Output:")
print(np.round(o, 3))

Epoch 1
w1=
 [[ 0.4161105   0.71847888 -0.0027131 ]
 [ 0.30151424  0.14541439  0.08965393]] 
w2=
 [[0.15154525]
 [0.30979298]
 [0.36637397]]

Epoch 10
w1=
 [[ 0.41462765  0.71231763 -0.01428084]
 [ 0.30019247  0.14203844  0.07857921]] 
w2=
 [[-0.03580757]
 [ 0.11678968]
 [ 0.20206433]]

Final Output:
[[0.075]
 [0.952]
 [0.952]
 [0.025]]


In [ ]:
McCulloch-Pitts – AND Gate
Defined a step function that returns 1 if net ≥ threshold
Set weights: w1 = 1, w2 = 1
Set threshold: 2
Loop through all input combinations (0,0), (0,1), (1,0), (1,1)
For each input:
Calculate: net = x1*w1 + x2*w2
Pass net into step function
Only when net = 2 → output = 1
So only (1,1) gives output 1

👉 “AND logic is implemented using weights and threshold”

🔹 McCulloch-Pitts – OR Gate
Same step function is used
Changed only:
threshold = 1
For each input:
Calculate same net
If any input is 1 → net ≥ 1 → output = 1

👉 “Only threshold is changed to convert AND into OR”

🔹 McCulloch-Pitts – Loan Approval
Used 3 inputs: x1, x2, x3
Assigned equal weights: w1 = w2 = w3 = 1
Threshold set to 2
Loop through all 8 combinations
Compute:
net = x1 + x2 + x3
If net ≥ 2 → Approve, else Reject

👉 “At least 2 conditions must be satisfied for approval”

🔹 Perceptron – AND Gate
Defined inputs and correct outputs
Initialized weights and bias to 0
For each epoch:
Calculate:
net = x1*w1 + x2*w2 + bias
Apply step function → output
Compute error:
error = target - output
Update weights:
w += lr * error * input
Update bias

👉 “Weights are learned automatically using error correction”

🔹 Perceptron – OR Gate
Same training process as AND
Only changed:
Target values → [0,1,1,1]
Perceptron updates weights based on new targets

👉 “Same algorithm, different targets → different logic learned”

🔹 Perceptron – Loan Approval
Took user input for:
Credit score, income, debt
Used real-valued weights:
2.5, 1.8, 1.2
Bias = -3
Compute:
net = weighted sum + bias
Apply step function:
net ≥ 0 → Approve
else → Reject

👉 “Higher weight means more importance in decision”

🔹 XOR using Backpropagation ⭐
Defined input-output for XOR
Initialized weights randomly
Used sigmoid activation function
Forward pass:
Input → hidden layer → output
Compute error:
error = actual - predicted
Backpropagation:
Adjust weights using gradients
Repeat for many iterations

👉 “Uses multi-layer network to learn non-linear XOR pattern”