<a href="https://colab.research.google.com/github/Swayam17o5/DL1/blob/main/RNN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from sklearn.metrics import classification_report
texts = [
    "I love this movie",
    "This film is great",
    "I hate this movie",
    "This film is terrible",
    "Amazing storyline and acting",
    "Worst movie ever",
    "A truly captivating story",
    "What a waste of time",
    "The acting was superb",
    "Could not stand this movie",
    "Highly recommend it",
    "I really love this"
]

labels = [1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1]

df = pd.DataFrame({"text": texts, "label": labels})
tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

max_len = 6
X = pad_sequences(sequences, maxlen=max_len, padding='post')

y = np.array(labels)

print("Padded Sequences:\n", X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = Sequential()

model.add(Embedding(input_dim=1000, output_dim=32))

model.add(SimpleRNN(16, activation='tanh'))

model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X, y, epochs=10, batch_size=2, verbose=1)
model.summary()
loss, acc = model.evaluate(X_test, y_test)
print("\nTest Accuracy:", acc)
def predict_sentiment(text):
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=max_len, padding='post')
    pred = model.predict(padded, verbose=0)[0][0]

    return "Positive" if pred > 0.5 else "Negative"

test_samples = [
    "I really love this"
]

print("\nSample Predictions:\n")
for t in test_samples:
    print(f"{t} --> {predict_sentiment(t)}")

Padded Sequences:
 [[ 4  5  2  3  0  0]
 [ 2  6  7 10  0  0]
 [ 4 11  2  3  0  0]
 [ 2  6  7 12  0  0]
 [13 14 15  8  0  0]
 [16  3 17  0  0  0]
 [ 9 18 19 20  0  0]
 [21  9 22 23 24  0]
 [25  8 26 27  0  0]
 [28 29 30  2  3  0]
 [31 32 33  0  0  0]
 [ 4 34  5  2  0  0]]
Epoch 1/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.5000 - loss: 0.6974
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6663 
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6434 
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.6184 
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5929 
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5606 
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5273     
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4821 
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (2, 6, 32)             │        32,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (2, 16)                │           784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (2, 1)                 │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 98,405 (384.40 KB)

 Trainable params: 32,801 (128.13 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 65,604 (256.27 KB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 501ms/step - accuracy: 1.0000 - loss: 0.2789

Test Accuracy: 1.0

Sample Predictions:

I really love this --> Positive


In [ ]:
Dataset Creation

Created small dataset:

texts = [...]
labels = [...]

Labels:

1 → Positive
0 → Negative

Stored in:

pandas DataFrame

👉 Simple binary classification dataset

🔹 Tokenization (Text → Numbers)
Tokenizer(num_words=1000, oov_token="<OOV>")
Converts words → integers
<OOV> handles unknown words

Example:

"I love movie" → [5, 12, 33]
🔹 Convert to Sequences
texts_to_sequences(texts)
Each sentence becomes numeric sequence
🔹 Padding Sequences
pad_sequences(maxlen=6, padding='post')
All sentences made length = 6
Short sentences → padded with 0

👉 Required for fixed-size input

🔹 Train-Test Split
train_test_split(test_size=0.2)
80% training
20% testing
🔹 Model Architecture
Embedding → SimpleRNN → Dense
🔸 Embedding Layer
Embedding(input_dim=1000, output_dim=32)
Converts word indices → dense vectors
Learns word meaning
🔸 SimpleRNN Layer
SimpleRNN(16, activation='tanh')
Processes sequence step-by-step
Captures basic order of words

👉 Simpler than LSTM/GRU

🔸 Dense Layer
Dense(1, activation='sigmoid')
Outputs single value:

0.5 → Positive

≤ 0.5 → Negative
🔹 Model Compilation
optimizer = adam
loss = binary_crossentropy
Binary classification problem
Accuracy used as metric
🔹 Model Training
model.fit(X, y, epochs=10, batch_size=2)
Trains model on dataset
Learns sentiment patterns
🔹 Model Summary
model.summary()
Shows:
Layers
Parameters
🔹 Model Evaluation
model.evaluate(X_test, y_test)
Prints test accuracy
🔹 Prediction Function
predict_sentiment(text)

Steps:

Convert text → sequence
Pad sequence
Predict using model

Apply threshold:

pred > 0.5 → Positive
🔹 Sample Output
"I really love this" → Positive